/* file: C:/Workspace/_EA4/T1xx/GM_T1XX_EPS_RH850_Working/GM_T1XX_EPS_RH850/generate/nontrustfct.h */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: C:/Users/kzdyfh/AppData/Local/Temp/Cfg_Gen-1475858681492-8/AutosarFiles_ValGen-1475864902407-0/Os_ECUC_4.0.3_5597378437960559406.arxml */
/* Generation time: Fri Oct 07 14:28:24 2016 */
/* Unlimited license CBD1400351 for Nexteer Automotive, Project License, EPS */
/* Implementation: RH850_P1M */
/* Version of general code: 9.01.04 */
/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with message 0883,
 * but there is a double include prevention and therefore the message is considered to be wrong. */
#if ! defined __NONTRUSTFCT_H__   /* PRQA S 0883 EOF */ 
#define __NONTRUSTFCT_H__
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define NtWrapS_CanStop   0
#define NtWrapS_CmnMfgSrv_CallSvc10   1
#define NtWrapS_CustDiagc_ClrAllDiagc   2
#define NtWrapS_CustDiagc_ClrHwAgTrimVal   3
#define NtWrapS_CustDiagc_DemDcmDisableDTCSetting   4
#define NtWrapS_CustDiagc_DemDcmEnableDTCSetting   5
#define NtWrapS_CustDiagc_DiDtcRecUpd   6
#define NtWrapS_CustDiagc_EnaDtcRecUpd   7
#define NtWrapS_CustDiagc_GmFctDiReq   8
#define NtWrapS_CustDiagc_UpdHwAgTrimVal   9
#define NtWrapS_GMLANInit   10
#define NtWrapS_GmMsg778BusHiSpd_DtcStsChgd   11
#define NtWrapS_NvM_EraseNvBlock   12
#define NtWrapS_NvM_GetDataIndex   13
#define NtWrapS_NvM_GetErrorStatus   14
#define NtWrapS_NvM_InvalidateNvBlock   15
#define NtWrapS_NvM_ReadBlock   16
#define NtWrapS_NvM_SetBlockProtection   17
#define NtWrapS_NvM_SetDataIndex   18
#define NtWrapS_NvM_SetRamBlockStatus   19
#define NtWrapS_NvM_WriteBlock   20
#define NtWrapS_Rte_Call_CopyCalPageReq_Oper   21
#define NtWrapS_Rte_Call_SetCalPageReq_Oper   22
#define NtWrapS_StHlthSigStc_ClrDataSample   23
#define NtWrapS_StHlthSigStc_UpdDataSample   24
#define NtWrapS_StHlthSigStc_UpdNvmPim   25
#define NtWrapS_SyncCrc_GetAvlCrcHwUnit   26
#define NtWrapS_SyncCrc_RelsCrcHwUnit   27

void NONTRUSTED_NtWrapS_CanStop(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CmnMfgSrv_CallSvc10(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_ClrAllDiagc(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_ClrHwAgTrimVal(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_DemDcmDisableDTCSetting(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_DemDcmEnableDTCSetting(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_DiDtcRecUpd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_EnaDtcRecUpd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_GmFctDiReq(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_CustDiagc_UpdHwAgTrimVal(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_GMLANInit(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_GmMsg778BusHiSpd_DtcStsChgd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_EraseNvBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_GetDataIndex(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_GetErrorStatus(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_InvalidateNvBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_ReadBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_SetBlockProtection(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_SetDataIndex(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_SetRamBlockStatus(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_NvM_WriteBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_Rte_Call_CopyCalPageReq_Oper(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_Rte_Call_SetCalPageReq_Oper(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_StHlthSigStc_ClrDataSample(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_StHlthSigStc_UpdDataSample(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_StHlthSigStc_UpdNvmPim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_SyncCrc_GetAvlCrcHwUnit(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
void NONTRUSTED_NtWrapS_SyncCrc_RelsCrcHwUnit(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);

#endif /* ! defined __NONTRUSTFCT_H__ */
