/* file: C:/_synergy/G2KCAT3_CZ8L9T/GM_G2KCA_EPS_RH850/generate/osStacks.c */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: C:/Users/cz8l9t/AppData/Local/Temp/Cfg_Gen-1484853116431-5/AutosarFiles_ValGen-1484860851174-0/Os_ECUC_4.0.3_2798538737394265774.arxml */
/* Generation time: Thu Jan 19 16:20:53 2017 */
/* Unlimited license CBD1400351 for Nexteer Automotive, Project License, EPS */
/* Implementation: RH850_P1M */
/* Version of general code: 9.01.04 */
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osStacks.h"
#else
 #include <osStacks.h>
#endif

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel13_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel13_c0 [128]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel14_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel14_c0 [128]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel15_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel15_c0 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel3_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel3_c0 [128]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osSystemStack_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osSystemStack_c0 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl100"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl100 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl101"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl101 [512]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl102"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl102 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl103"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl103 [512]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl104"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl104 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl105"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl105 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl106"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl106 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl107"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl107 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl60"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl60 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl61"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl61 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl62"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl62 [512]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl63"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl63 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackosSystemApplicationCore00"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackosSystemApplicationCore00 [4]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackosSystemApplicationCore01"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackosSystemApplicationCore01 [4]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

